import fs from "node:fs/promises";
import path from "node:path";
import { z } from "zod";

export type SessionBackupMetadataSnapshot = {
  kind: "directory" | "tar_gz";
  path: string;
};

export type SessionBackupMetadataCheckpoint = {
  id: string;
  index: number;
  createdAt: string;
  trigger: "initial" | "auto" | "manual";
  changed: boolean;
  patchBytes: number;
  fingerprint: string;
  snapshot: SessionBackupMetadataSnapshot;
};

export type SessionBackupMetadata = {
  version: 1;
  sessionId: string;
  workingDirectory: string;
  createdAt: string;
  state: "active" | "closed";
  closedAt?: string;
  originalFingerprint?: string;
  originalSnapshot: SessionBackupMetadataSnapshot;
  checkpoints: SessionBackupMetadataCheckpoint[];
};

/**
 * Snapshot paths are always generated by us as relative paths under the backup
 * session directory. Backup metadata is attacker-tamperable in our threat model,
 * so a snapshot path that is absolute or escapes the session directory (`..`) is
 * rejected at load time. Both separators are checked so a tampered POSIX archive
 * cannot smuggle a Windows-style traversal (or vice versa).
 */
function isContainedRelativeSnapshotPath(candidate: string): boolean {
  if (path.isAbsolute(candidate)) return false;
  if (/^[a-zA-Z]:/.test(candidate)) return false;
  if (candidate.startsWith("/") || candidate.startsWith("\\")) return false;
  return !candidate.split(/[\\/]+/).some((segment) => segment === "..");
}

const snapshotRefSchema = z.object({
  kind: z.enum(["directory", "tar_gz"]),
  path: z.string().min(1).refine(isContainedRelativeSnapshotPath, {
    message: "snapshot path must be a relative path contained within the backup session directory",
  }),
});

const sessionBackupMetadataCheckpointSchema = z
  .object({
    id: z.string().min(1),
    index: z.number(),
    createdAt: z.string().min(1),
    trigger: z.enum(["initial", "auto", "manual"]),
    changed: z.boolean(),
    patchBytes: z.number(),
    fingerprint: z.string().min(1),
    snapshot: snapshotRefSchema,
  })
  .passthrough();

const sessionBackupMetadataSchema = z
  .object({
    version: z.literal(1),
    sessionId: z.string().min(1),
    workingDirectory: z.string().min(1),
    createdAt: z.string().min(1),
    state: z.enum(["active", "closed"]),
    closedAt: z.string().optional(),
    originalFingerprint: z.string().min(1).optional(),
    originalSnapshot: snapshotRefSchema,
    checkpoints: z.array(sessionBackupMetadataCheckpointSchema),
  })
  .passthrough();

const errorWithCodeSchema = z.object({ code: z.string() }).passthrough();

export async function writeJson(filePath: string, value: unknown): Promise<void> {
  await fs.writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`, {
    encoding: "utf-8",
    mode: 0o600,
  });
  try {
    await fs.chmod(filePath, 0o600);
  } catch {
    // best effort only
  }
}

export async function readMetadata(filePath: string): Promise<SessionBackupMetadata | null> {
  try {
    const raw = await fs.readFile(filePath, "utf-8");
    let payload: unknown;
    try {
      payload = JSON.parse(raw);
    } catch (error) {
      throw new Error(`Invalid backup metadata JSON at ${filePath}: ${String(error)}`);
    }
    const parsed = sessionBackupMetadataSchema.safeParse(payload);
    if (!parsed.success) {
      throw new Error(
        `Invalid backup metadata schema at ${filePath}: ${parsed.error.issues[0]?.message ?? "validation_failed"}`,
      );
    }
    return parsed.data;
  } catch (error) {
    const parsedCode = errorWithCodeSchema.safeParse(error);
    const code = parsedCode.success ? parsedCode.data.code : undefined;
    if (code === "ENOENT") return null;
    throw error;
  }
}
