import { z } from "zod";

import {
  jsonRpcNotificationSchemas,
  jsonRpcRequestSchemas,
  jsonRpcResultSchemas,
  jsonRpcServerRequestSchemas,
  jsonRpcSchemaBundleSchema,
} from "./schema";

function formatMethodName(value: string): string {
  return value
    .replace(/[^a-zA-Z0-9]+(.)/g, (_match, next: string) => next.toUpperCase())
    .replace(/[^a-zA-Z0-9]/g, "")
    .replace(/^[a-z]/, (first) => first.toUpperCase());
}

function stripSchemaKeyword(record: Record<string, unknown>): Record<string, unknown> {
  const { $schema: _ignored, ...rest } = record;
  return rest;
}

function renderSchemaAlias(prefix: string, method: string, schema: z.ZodTypeAny): string {
  const name = `${formatMethodName(method)}${prefix}`;
  return `export type ${name} = ${JSON.stringify(stripSchemaKeyword(z.toJSONSchema(schema) as Record<string, unknown>))};`;
}

export function buildJsonRpcJsonSchemaArtifact(): string {
  const schema = stripSchemaKeyword(z.toJSONSchema(jsonRpcSchemaBundleSchema) as Record<string, unknown>);
  return `${JSON.stringify(schema, null, 2)}\n`;
}

export function buildJsonRpcTypeScriptArtifact(): string {
  const requestMethods = Object.keys(jsonRpcRequestSchemas);
  const notificationMethods = Object.keys(jsonRpcNotificationSchemas);
  const serverRequestMethods = Object.keys(jsonRpcServerRequestSchemas);
  const resultMethods = Object.keys(jsonRpcResultSchemas);

  return [
    "// Generated by scripts/generate_ws_jsonrpc_schema.ts",
    "",
    `export type JsonRpcRequestMethod = ${requestMethods.map((method) => JSON.stringify(method)).join(" | ")};`,
    `export type JsonRpcNotificationMethod = ${notificationMethods.map((method) => JSON.stringify(method)).join(" | ")};`,
    `export type JsonRpcServerRequestMethod = ${serverRequestMethods.map((method) => JSON.stringify(method)).join(" | ")};`,
    `export type JsonRpcResultMethod = ${resultMethods.map((method) => JSON.stringify(method)).join(" | ")};`,
    "",
    ...requestMethods.map((method) => renderSchemaAlias("RequestSchema", method, jsonRpcRequestSchemas[method as keyof typeof jsonRpcRequestSchemas])),
    ...notificationMethods.map((method) => renderSchemaAlias("NotificationSchema", method, jsonRpcNotificationSchemas[method as keyof typeof jsonRpcNotificationSchemas])),
    ...serverRequestMethods.map((method) => renderSchemaAlias("ServerRequestSchema", method, jsonRpcServerRequestSchemas[method as keyof typeof jsonRpcServerRequestSchemas])),
    ...resultMethods.map((method) => renderSchemaAlias("ResultSchema", method, jsonRpcResultSchemas[method as keyof typeof jsonRpcResultSchemas])),
    "",
  ].join("\n");
}
