import {
  jsonRpcControlRequestSchemas,
  jsonRpcControlResultSchemas,
  skillContentEventSchema,
  skillInstallationEventSchema,
  skillInstallPreviewEventSchema,
  skillInstallUpdateCheckEventSchema,
  skillsCatalogEventSchema,
  skillsListEventSchema,
} from "../../shared/jsonrpcControlSchemas";

export const jsonRpcSkillsRequestSchemas = {
  "cowork/skills/catalog/read": jsonRpcControlRequestSchemas["cowork/skills/catalog/read"],
  "cowork/skills/list": jsonRpcControlRequestSchemas["cowork/skills/list"],
  "cowork/skills/read": jsonRpcControlRequestSchemas["cowork/skills/read"],
  "cowork/skills/disable": jsonRpcControlRequestSchemas["cowork/skills/disable"],
  "cowork/skills/enable": jsonRpcControlRequestSchemas["cowork/skills/enable"],
  "cowork/skills/delete": jsonRpcControlRequestSchemas["cowork/skills/delete"],
  "cowork/skills/installation/read": jsonRpcControlRequestSchemas["cowork/skills/installation/read"],
  "cowork/skills/install/preview": jsonRpcControlRequestSchemas["cowork/skills/install/preview"],
  "cowork/skills/install": jsonRpcControlRequestSchemas["cowork/skills/install"],
  "cowork/skills/installation/enable": jsonRpcControlRequestSchemas["cowork/skills/installation/enable"],
  "cowork/skills/installation/disable": jsonRpcControlRequestSchemas["cowork/skills/installation/disable"],
  "cowork/skills/installation/delete": jsonRpcControlRequestSchemas["cowork/skills/installation/delete"],
  "cowork/skills/installation/update": jsonRpcControlRequestSchemas["cowork/skills/installation/update"],
  "cowork/skills/installation/copy": jsonRpcControlRequestSchemas["cowork/skills/installation/copy"],
  "cowork/skills/installation/checkUpdate": jsonRpcControlRequestSchemas["cowork/skills/installation/checkUpdate"],
} as const;

export const jsonRpcSkillsResultSchemas = {
  "cowork/skills/catalog/read": jsonRpcControlResultSchemas["cowork/skills/catalog/read"],
  "cowork/skills/list": jsonRpcControlResultSchemas["cowork/skills/list"],
  "cowork/skills/read": jsonRpcControlResultSchemas["cowork/skills/read"],
  "cowork/skills/disable": jsonRpcControlResultSchemas["cowork/skills/disable"],
  "cowork/skills/enable": jsonRpcControlResultSchemas["cowork/skills/enable"],
  "cowork/skills/delete": jsonRpcControlResultSchemas["cowork/skills/delete"],
  "cowork/skills/installation/read": jsonRpcControlResultSchemas["cowork/skills/installation/read"],
  "cowork/skills/install/preview": jsonRpcControlResultSchemas["cowork/skills/install/preview"],
  "cowork/skills/install": jsonRpcControlResultSchemas["cowork/skills/install"],
  "cowork/skills/installation/enable": jsonRpcControlResultSchemas["cowork/skills/installation/enable"],
  "cowork/skills/installation/disable": jsonRpcControlResultSchemas["cowork/skills/installation/disable"],
  "cowork/skills/installation/delete": jsonRpcControlResultSchemas["cowork/skills/installation/delete"],
  "cowork/skills/installation/update": jsonRpcControlResultSchemas["cowork/skills/installation/update"],
  "cowork/skills/installation/copy": jsonRpcControlResultSchemas["cowork/skills/installation/copy"],
  "cowork/skills/installation/checkUpdate": jsonRpcControlResultSchemas["cowork/skills/installation/checkUpdate"],
} as const;
